---
title: "Micro-project 2025 : MODESTA"
author: Eliot Boulaire
date: last-modified
editor: visual
toc: true
format:
  html: default
  pdf: default
---

# Size-structured demographic models on marine phase of Atlantic salmon

Spé/M2 SHA - Option REA\
2023 - 2024\
UE MODH - UC : "Quantitative analysis for resources and fisheries modelisation"

## Context

### Environnemental context

Aquatic ecosystems are increasingly impacted by anthropogenic pressures, such as overexploitation, habitat degradation, and climate change. These disturbances significantly affect ecosystem functioning and the sustainability of natural resources (Worm et al., 2006; IPBES, 2019).

Diadromous fish, such as the Atlantic salmon (Salmo salar), are especially vulnerable due to their reliance on both marine and continental ecosystems. Classified as ‘Near Threatened’ by the IUCN, salmon have faced threats in recent decades linked to changes in the marine ecosystem (recently updated from ‘Least Concern’ to ‘Near Threatened’ in 2023). Salmon populations have experienced substantial declines, particularly due to reduced survival rates of young salmon during the marine phase (Chaput, 2012; ICES, 2017). This decline is accompanied by shifts in life-history traits, such as accelerated maturation (Jonsson et al., 2016; Olmos et al., 2019) and reduced adult size (Todd et al., 2012; Bal et al., 2017; Vollset et al., 2022), leading to lower fecundity (Hanson et al., 2020) and a loss of intra-population diversity, which weakens the 'portfolio effect' (Carlson and Satterthwaite, 2011; Schindler et al., 2010). These changes ultimately compromise population resilience, making them more sensitive to environmental pressures and exploitation.

**In this context, gaining a deeper understanding of the mechanisms that drive salmon populations' responses to global change is crucial. This knowledge will improve our ability to assess their current state and inform the development of effective management strategies.**

### Main hypothesis

The rapid changes observed in the structure and functioning of salmon populations suggest a response to alterations in the ecosystem, particularly a decline in the quantity and quality of trophic resources available during the marine phase of the life cycle (ICES, 2017).

Available data indicates that growth plays a crucial role in the main demographic transitions throughout the salmon life cycle, influenced by trade-offs specific to each sex.

-   Growth is a key integrative trait of global change (including climate change) that reflects an individual's ability to acquire resources from its environment, assimilate them, and allocate them to various functions.

-   Growth is also a life-history trait (LHT) influenced by trade-offs with other major LHTs, such as individual mortality (Friedland et al., 2009) or size and age at maturation (Mobley et al., 2021), among others.

Specifically, the size of individuals during the smolt migration to the sea increases the probability of survival and successful return (i.e., "bigger is better": Gregory et al., 2019; Simmons et al., 2021). Additionally, the decision to sexually mature, which determines the return for reproduction, is partly influenced by reaching a size threshold at the end of the first summer at sea, with larger individuals having a greater likelihood of triggering maturation (Mobley et al., 2021; Tréhin et al., 2023). This threshold is typically higher for females, who, on average, have a lower probability of maturing after just one winter at sea compared to males of similar size.

**Given the importance of growth in demographic processes, any change in growth due to environmental variations will have significant impacts on population structure and, ultimately, population dynamics.**

### Modelisation context

However, current population models used for fish stock assessments struggle to explicitly account for the variability of phenotypic traits (such as size) between individuals and/or over time. By neglecting variations in size, these models generate biased estimates of population dynamics, limiting the relevance and accuracy of their projections. In contrast, individual-based models have investigated the influence of growth on the life histories of Atlantic salmon, but their complexity makes them challenging to apply for quantitative assessments based on field data.

**To address this issue, the development of population models structured by life stages and size is essential for improving our understanding of observed variations and enhancing our ability to predict population responses under multiple pressures. The Integral Projection Models (IPMs) approach is proposed as a promising alternative. Positioned between individual-based models and age-structured models in terms of complexity, IPMs offer a more effective framework for incorporating the impacts of growth on population dynamics.**

### Micro-project framework

This micro-project is part of a broader framework of a PhD research aiming to analyze the influence of individual growth variations on the population dynamics of Atlantic salmon. The goal is to improve the tools used to assess their status and propose more robust management measures adapted to environmental pressures. The first step of this project involves characterizing key demographic transitions (survival and maturation) during the marine phase of Atlantic salmon in relation to individual size.

A major challenge lies in drawing conclusions about the hidden processes of survival and maturation that occur between the smolt stage, during their migration to the sea, and the adult stage, when they return to rivers after their marine phase. To address this challenge, indirect information on individual growth during these hidden stages is obtained through the analysis of archival tissues, such as scales, which allow the reconstruction of individual life histories.

**A model structured by age, stage, sex, and size has been developed to accommodate the complex life cycle of Atlantic salmon**. It was built within an integrated hierarchical statistical modeling framework. This approach is well-suited for combining diverse sources of observations to infer hidden demographic processes (Schaub & Abadi, 2011; Zipkin et al., 2019).

## Objectives

[Current modeling has limitations :]{.underline}

While it accounts for annual data and sex proportions, it does not incorporate these factors into the formalization of size-dependent survival and maturation transitions. **The first objective** is to improve the modeling of survival and maturation processes by integrating annual variations and sex differences, based on existing literature.

The current model uses indirect size information from scales, assuming an isometric relationship between scale size and body size. However, this assumption appears inconsistent with findings in the literature. **The second objective** is to introduce three back-calculation models for estimating salmon body size from scale size, chosen based on literature, and assess the variability introduced by their application.

Due to the current reliance on scale size modeling, no direct links with population state indicators used in management could be established. **The final objective** is to leverage the three back-calculation models to develop a direct connection to egg deposition (a proxy for fecundity and population renewal), which will provide valuable insights for management decisions.

## Resources

### Study site

This work is based on long-term monitoring data (24 years of smolt cohorts from 1996 to 2019) of natural salmon populations collected by the *Observatoire de Recherche en Environnement petits Fleuves Côtiers* (ORE DiaPFC) and the *Centre National pour l’Interprétation des Captures de Salmonidés* (CNICS). These data are centralized in information systems managed by INRAE.

Specifically, the data pertain to the Scorff salmon population, a river in the Morbihan region of Brittany. The Scorff drains a 483 km² basin over a 77 km course, joining the Blavet at a common estuary near Lorient. A migration monitoring station has been operational since 1994 at the *Moulin des Princes* (MdP) site in Pont-Scorff. This station enables the trapping of smolts during downstream migration and adults during upstream migration. Each captured salmon is measured, weighed, and has scales sampled before being released. The collected scales are archived in the ichthyological collection COLISA (*Marchand et al., 2021*), managed by INRAE and OFB.

### Data

The data, which has not yet been published, will be shared with you via USB during the first session. Please ensure that the data is deleted after the completion of the course.

#### Abundance estimations

The counting data collected at the MdP station are imperfect, as some salmon can bypass the trap, particularly during periods of heavy rainfall. To address this, mark-recapture experiments are conducted to estimate:

-   **Trap efficiency** based on flow conditions,

-   **The abundance of migrating smolts** (across all age classes),

-   **Adult returns**, categorized into two age classes: 1SW (one-sea-winter) and 2SW (two-sea-winter).

These estimates, derived from 24 years of data, are produced using Bayesian hierarchical models that account for imperfect detection (*Buoro et al., 2019*).

#### Molecular sexing

Sexual dimorphism in salmon at the time of trapping (both at the smolt and adult stages) is not pronounced enough to allow reliable sex identification.

To address this, a sample of 30 scales from 30 different individuals per smolt cohort year and life stage was selected to determine sex using DNA extracted from scale tissues (*i.e.*, molecular sexing: Besnard et al., 2023). However, reliable sex identification was only possible for a subset of the sample, as DNA extracted from older scales was often too degraded. Additionally, since sexing was not performed after 2018, limited information is available for the most recent cohorts.

In total, the sex of only ... individuals could be identified, with significant temporal variation (see figure).

#### Scale size

The model uses individual data from scale readings to estimate the size structure of the population. A sample of 30 scales from 30 different individuals per smolt cohort year and life stage was selected to determine the growth ring sizes at various audit stages (see figure). Scales are calcified structures that grow alongside the individual, are easy to collect, and have minimal impact on the fish's life.

The scales are collected from a "standard zone" (see figure) on the fish's body, where scales first develop during the fry stage. The scale size from this area is the most strongly correlated with the salmon's body size (Baglinière et al., 1985; Shearer, 1992).

### Model

Le modèle est formulé dans le cadre d’un modèle de population intégré à espace d'état (modèle hiérarchique) bayésien qui permet d’intégrer différentes sources de données (l’abondance, le rapport des sexes et la structure de taille) et les erreurs d’observation associées, afin d’estimer la dynamique de population représentée par des stades et des transitions démographiques latentes, non-directement observables (Figure 2).

Ce modèle est composé de 3 stades observées (smolts, 1HM et 2HM) et 4 stades latents (smolts survivants, post-smolts à la maturation, post-smolts maturant et post-smolts non-maturant) (Figure 1 et 2). La structure en taille est représentée à chaque stade par k = 50 classes. Ce niveau de discrétisation offre un bon compromis entre la modélisation des transitions taille-dépendantes sous la forme de taux de transition (taux de survie, taux de maturation) dépendant explicitement de la classe de taille et l'efficacité computationnelle.

Ce modèle est également sexé, les abondances dans chaque stade sont représentées séparément pour les mâles et les femelles (indice s). Le modèle est également structuré en fonction du temps, représenté par l’année de dévalaison des smolts, soit 24 cohortes (indices t). L'abondance et les transitions sont représentées indépendamment pour chaque cohorte. A noter cependant que la croissance entre les stades n’est pas représentée dans ce modèle. 

Pour chaque cohorte t, le premier stade représenté est le stade de smolt migrant (au printemps de l’année t) (Figure 2). Les smolts passent alors un premier été en mer jusqu’à la fin de l’été de l’année t (novembre) durant lequel ils sont soumis à une première transition démographique de survie jusqu’au stade de smolt survivants (Figure 2). Après le premier été en mer, les smolts survivants intègrent tous le stade post-smolts à la maturation, c'est-à-dire des smolts qui réalisent la transition démographique avec une décision de maturation ou non. Ces post-smolts ont des structures de taille différentes du stade précédent, cependant l’étape de croissance entre les smolts survivants et les post-smolts à la maturation n’est pas modélisée. Les post-smolts maturants retourneront dans leur rivière natale comme adultes au stade de retour après 1HM (juillet de l’année t+1), conditionnellement à une survie post-maturation fixe. Les post-smolts non-maturants retourneront au stade adulte de retour après 2HM (mai de l’année t+2) (Figure 2), conditionnellement à une survie post-maturation fixe. Afin de limiter la confusion dans l’estimation statistique des deux taux de transition précédents, la survie post-maturation est considérée connue et ne varie ni en fonction de la taille, ni en fonction du sexe, ni en fonction de la cohorte. Conditionnellement aux taux de transitions précédents, les transitions sont modélisées comme déterministes. Les taux de survie et de maturation sont appliqués de façon multiplicative sur les abondances pour les différents stades (observé ou latent), sexes (s), classes de taille (l) et cohorte (t). Ces deux transitions sont potentiellement dépendantes de la classe de taille, potentiellement différentes entre les mâles et les femelles et différentes entre les cohortes de smolts. L’étape de croissance entre les post-smolts maturants ou non-maturants et les adultes de retour en 1HM ou 2HM n’est pas modélisée.

## Guidelines

1.  qzd

2.  qzd

3.  dqz

## References
